-- MySQL Script generated by MySQL Workbench
-- Tue Jan 12 23:11:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT(100) NULL,
  `foto` VARCHAR(100) NULL,
  `telefone` INT NOT NULL,
  `cep` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `role` VARCHAR(25) NOT NULL,
  `tipo_do_servico` VARCHAR(45) NOT NULL,
  `qts_servicos` INT NOT NULL AUTO_INCREMENT,
  `redes_sociais` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`feedback1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`feedback1` (
  `idfeedback` INT NOT NULL,
  `feedbackcol` VARCHAR(200) NOT NULL,
  `avaliacao` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`idfeedback`),
  INDEX `fk_feedback_usuario_idx` (`usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_usuario`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `mydb`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`imagens` ;

CREATE TABLE IF NOT EXISTS `mydb`.`imagens` (
  `idimagens` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`idimagens`),
  INDEX `fk_imagens_usuario1_idx` (`usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_imagens_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `mydb`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
